import * as express from 'express';
import * as bodyParser from 'body-parser';
import { RegisterRoutes } from '../routes';
import * as cors from 'cors';
import * as path from 'path';
import useSwagger from './swagger';

export default (app: express.Express): void => {
    app.use(bodyParser.json());
    app.use(cors());
    app.use(express.static(path.join(__dirname, '../public')));

    //register all routes from the routes generated by tsoa
    RegisterRoutes(app);

    console.log('✌️ Express loaded.');

    useSwagger(app);
    console.log('📗 Swagger loaded.');

};